# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"

    config.vm.provision "shell" do |s|
      s.path = "vagrant_files/install_maven.sh"
    end

    config.vm.provision "shell" do |s|
      s.path = "vagrant_files/install_xfce.sh"
    end

    config.vm.network "forwarded_port", guest: 8080, host: 8080
  
    virtualbox_name = "JavaFX"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = virtualbox_name
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--vram", "12"]
    end
    config.vm.post_up_message = "#{virtualbox_name} machine is up and running!"
end
